version: '3'
services:
  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - caddy
    volumes:
      - .:/usr/src/app
    env_file:
      - stack.env
    labels:
      caddy: "social-commerce-api.aomdev.com"
      caddy.reverse_proxy: "{{upstreams 3000}}"
networks:
  caddy:
    external: true