version: '3'
services:
  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - caddy
    volumes:
      - api_data:/usr/src/app
    labels:
      caddy: "social-commerce.api-dev.aomdev.com"
      caddy.reverse_proxy: "{{upstreams 3000}}"
networks:
  caddy:
    external: true
volumes:
  api_data: {}