export enum EActionPayload {
    _TEST = "USER-DEFINED-PAYLOAD",
    NOTHING = "NOTHING_PAYLOAD",
    WELCOME = "WELCOME_PAYLOAD",
    GET_STARTED = "GET_STARTED_PAYLOAD",
    ADD_TO_CART = "ADD_TO_CART_PAYLOAD",
    SHOW_PRODUCT = "SHOW_PRODUCT_PAYLOAD",
    VIEW_CART = "VIEW_CART_PAYLOAD",
    CONFIRM_ORDER = "CONFIRM_ORDER_PAYLOAD",
    CANCEL_ORDER = "CANCEL_ORDER_PAYLOAD",
    CREATE_ORDER = "CREATE_ORDER_PAYLOAD",
    ON_ORDER_PAID = "ON_ORDER_PAID_PAYLOAD",
};